# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f4dd977b4a844d2e35d44e82f787b01c"
name = "Discounto"
application_url = "https://discounto.onrender.com"
embedded = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_themes,read_discounts,write_discounts,write_app_proxy"
optional_scopes = [ ]
use_legacy_install_flow = false

[app_proxy]
url = "/proxy/better-discounts"
subpath = "better-discounts"
prefix = "apps"

[auth]
redirect_urls = [
  "https://discounto.onrender.com/auth/callback",
  "https://discounto.onrender.com/auth/shopify/callback",
  "https://discounto.onrender.com/api/auth/callback",
]

[build]
automatically_update_urls_on_dev = true
