api_version = "2026-07"

[[extensions]]
name = "t:name"
handle = "discounto-free-shipping"
uid = "870aa117-7a1c-2e67-4e91-16a5390ba2e9c7ee068e"
type = "function"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.delivery-options.discounts.generate.run"
  input_query = "src/cart_delivery_options_discounts_generate_run.graphql"
  export = "cart-delivery-options-discounts-generate-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.input.variables]
  namespace = "$app"
  key = "function-configuration"
